{
 "title": "Docker Statistics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_percent_ratio * 100",
     "legendFormat": "Memory Usage (in %)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio * 100",
     "legendFormat": "CPU Utilization (in %)"
    }
   ]
  },
  {
   "title": "Block IO in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_blockio_io_service_bytes_recursive_total{operation=\"read\"}[1m])) ",
     "legendFormat": "Read Operation"
    },
    {
     "expr": "sum(rate(container_blockio_io_service_bytes_recursive_total{operation=\"write\"}[1m])) ",
     "legendFormat": "Write Operation"
    }
   ]
  },
  {
   "title": "CPU usage in different modes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_kernelmode_nanoseconds_total[5m])",
     "legendFormat": "Kernel Mode"
    },
    {
     "expr": "rate(container_cpu_usage_usermode_nanoseconds_total[5m])",
     "legendFormat": "User Mode"
    }
   ]
  },
  {
   "title": "Container memory usage vs limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(container_memory_usage_total_bytes / container_memory_usage_limit_bytes) * 100",
     "legendFormat": "Total Bytes Read/Written"
    }
   ]
  },
  {
   "title": "Network bytes sent and received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_network_io_usage_rx_bytes_total{interface=\"eth0\"}[5m])\n"
    },
    {
     "expr": "rate(container_network_io_usage_tx_bytes_total{interface=\"eth0\"}[5m])",
     "legendFormat": "Network bytes received"
    }
   ]
  },
  {
   "title": "Network Packets dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_network_io_usage_rx_dropped_total{interface=\"eth0\"}[5m])",
     "legendFormat": "Network Bytes Dropped in Receiving"
    },
    {
     "expr": "rate(container_network_io_usage_tx_dropped_total{interface=\"eth0\"}[5m])",
     "legendFormat": "Network Bytes dropped in Sending"
    }
   ]
  }
 ]
}